# frozen_string_literal: true

source 'https://rubygems.org'

gem 'byebug'
gem 'rgeo', path: '/home/ian/workspace/land-registry/standard-reports-ui/data/boundary-line/vendor/rgeo'
gem 'rgeo-geojson', path: '/home/ian/workspace/land-registry/standard-reports-ui/data/boundary-line/vendor/rgeo-geojson'
gem 'rgeo-shapefile', path: '/home/ian/workspace/land-registry/standard-reports-ui/data/boundary-line/vendor/rgeo-shapefile'
gem 'simplify_rb'
