source 'https://rubygems.org'


gem 'rgeo', path: "/home/ian/workspace/land-registry/standard-reports-ui/data/boundary-line/vendor/rgeo"
gem 'rgeo-geojson', path: "/home/ian/workspace/land-registry/standard-reports-ui/data/boundary-line/vendor/rgeo-geojson"
gem 'rgeo-shapefile', path: "/home/ian/workspace/land-registry/standard-reports-ui/data/boundary-line/vendor/rgeo-shapefile"
gem 'byebug'
gem 'simplify_rb'
