plugins:
  - rubocop-rails

AllCops:
  Exclude:
    - app/models/regions_table.rb
    - app/models/locations_table.rb
    - bin/**/*
    - "node_modules/**/*"
    - "vendor/**/*"
    - data/**/*
    - "Gemfile"
  NewCops: enable

# Customize rules
Layout/LineLength:
  Max: 100
  AllowedPatterns: ['^(\s*#)']
  Exclude:
    - config/**/*
    - test/**/*

Lint/DuplicateBranch:
  Enabled: false

Metrics/AbcSize:
  Max: 30
  Exclude:
    - test/**/*
    - lib/tasks/**/*

Metrics/BlockLength:
  Max: 30
  Exclude:
    - test/**/*
    - lib/tasks/**/*

Metrics/ClassLength:
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Exclude:
    - test/**/*

Metrics/MethodLength:
  CountAsOne: ["array", "hash", "heredoc", "method_call"]
  Exclude:
    - test/**/*
    - lib/tasks/location.rake

Naming/MethodParameterName:
  Exclude:
    - test/**/*

Style/FormatStringToken:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
